config/routes.rb
LaptopShop1::Application.routes.draw do
  resources :line_items

  resources :carts

  get "users/new"

  get "welcome/home"
  get "welcome/thank_you"
  get "welcome/register"

  resources :products
  resources :users
  resources :sessions

  match '/your_cart' => "carts#your_cart", :as => "your_cart"
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  root :to => "welcome", :action => "home"

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

  has_many :products

  validates :email,
            :uniqueness => true,
            :length => {:within => 5..50},
            :format => {:with =>
                            /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i}
  validates :password,
            :confirmation => true,
            :length => {:within => 4..20},
            :presence => true


  attr_accessor :password
  before_save :encrypt_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end
  def authenticated?(password)
    self.hashed_password == encrypt(password + "ruby_rocks" + self.salt)
  end

  protected
  def encrypt_password
    return if password.blank?
    salt = generate_salt
    self.hashed_password = encrypt(password + "ruby_rocks" + salt)
  end
  def encrypt(string)
    Digest::SHA1.hexdigest(string)


  end

  def generate_salt
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    salt = ""
    1.upto(10) { |i| salt << chars[rand(chars.size-1)] }
    self.salt = salt
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

    @user = User.new
    end
    def create
      @user = User.new(params[:user])
      if @user.save
        redirect_to products_path, :notice => 'User creation successful!'
      else
        render :action => 'new'
      end
    end
  def index
    @users = User.find(:all)
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Create User</h1>
<% form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="actions">
      <%= f.submit "Create User"%>
    </div>
<% end %>
<%= link_to 'Back', products_path %>